# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pnewproduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='ponsale',
            field=models.BooleanField(default=False),
        ),
    ]
