# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171029_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=30, unique=True)),
                ('upassword', models.CharField(default='', max_length=25)),
                ('ugender', models.CharField(default='M', max_length=2)),
                ('uemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('ubirthday', models.DateField(null=True)),
            ],
        ),
    ]
