# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171103_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uemail',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
