# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20171115_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='pdesc',
            new_name='p_desc',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pimgs',
            new_name='p_imgs',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pname',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pnewproduct',
            new_name='p_newproduct',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='ponsale',
            new_name='p_onsale',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pprice',
            new_name='p_price',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='uname',
            new_name='user_account',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='uemail',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='ugender',
            new_name='user_gender',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='upassword',
            new_name='user_password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='ubirthday',
        ),
    ]
